### ISSUE TITLE
Multiple emulators

### ISSUE THREAD

**Issue by testingbot** [google/android-emulator-container-scripts#102]
Hi,

This is a great project!

How can we use this (rpc/webrtc) with multiple emulators?

- With `envoy.yaml` - how do we specify multiple endpoints and use javascript to connect to the correct endpoint?
- Similar for WebRTC + TURN/STUN, how do we use this in combination with multiple emulators? 

Thanks

**Comment by pokowaka** [comment]
Hi,

You will have to do the following things:

- Make sure your docker-compose exposes multiple emulators:

  emulator1:
    image: emulator_emulator:latest
    container_name: emulator_emulator
    networks:
      envoymesh:
        aliases:
          - emulator1
    devices: [/dev/kvm]
    shm_size: 128M
    expose:
      - "8556"


  emulator2:
    image: emulator_emulator:latest
    container_name: emulator_emulator
    networks:
      envoymesh:
        aliases:
          - emulator2
    devices: [/dev/kvm]
    shm_size: 128M
    expose:
      - "8556"

- Add this emulator to the envoy cluster:

```yaml

                # This is the emulator endpoint for grpc requests, you need to modify this 
                # and add an additional cluster.  Make sure to prefix it properly. For example here it is prefixed with emu1 for emulator 1.
              - match: { prefix: "emu1/android.emulation.control.EmulatorController" }
                route: 
                   cluster: emulator_service_grpc1
                   max_grpc_timeout: 0s

  - name: emulator_service_grpc . # Give this another name.
    connect_timeout: 0.250s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: emulator_service_grpc1 
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: emulator1 # This should point to the emulator
                port_value: 5556
```

- You must modify the javascript files to use the proper service:

i.e. 

```js
EMULATOR_GRPC = 'https://my-address/emu1'
EMULATOR_GRPC2 = 'https://my-address/emu2'
 this.auth = new TokenAuthService(EMULATOR_GRPC + "/token");
this.emulator1 = new EmulatorControllerService(EMULATOR_GRPC, this.auth);
this.emulator2 = new EmulatorControllerService(EMULATOR_GRPC2, this.auth);
``
Now you can add views like this:

```js
  <EmulatorScreen emulator={this.emulator1} auth={this.auth} />
  <EmulatorScreen emulator={this.emulator2} auth={this.auth} />
```


As for turn/stun. You must build the emulator with the proper --extra "-turncfg <cmd_to_obtain_json>" flag.
