### ISSUE TITLE
WebRTC view shows connected with no video, then drops connection

### ISSUE THREAD

**Issue by li-richard** [google/android-emulator-container-scripts#210]
![image](https://user-images.githubusercontent.com/9093478/96531219-fd7c0300-123d-11eb-81bf-bf8f6625ebd9.png)
![image](https://user-images.githubusercontent.com/9093478/96531239-08369800-123e-11eb-97ad-e2559beef824.png)

As seen in the images, the live view is showing as connected but with no video, then disconnected with a black screen.

Also attaching the full logs from

> docker logs cafc9ec1a59e | grep video

[logs.txt](https://github.com/google/android-emulator-container-scripts/files/5405853/logs.txt)

The logging just ends after failing to resolve the ICE connection. 

`video: (p2p_transport_channel.cc:1228): Failed to resolve ICE candidate hostname 211c4778-6954-4597-9902-2f48be491241.local with error -2`

Does this error mean that a TURN server is necessary? I was under the impression that it would work without one since both machines are on the same network.

**Comment by pokowaka** [comment]
We have seen some connections issues with docker. Could you perhaps share which version of docker and what OS you are using?

One work around to try to run docker with host networking.

**Comment by li-richard** [comment]
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

OS is `Red Hat Enterprise Linux Workstation release 7.6 (Maipo)`

**Comment by pokowaka** [comment]
We have multiple people running into port issues with docker and webrtc NAT. We are looking into moving the webrtc component to a separate container that can leverage host networking.

**Comment by nelenkov** [comment]
It would seem that docker internal network address sometimes? gets picked as a candidate, so it doesn't work even if a turn server is properly setup.

```
video: (Switchboard.cpp:124): send to: 3fb119ca-e9d1-4e29-b716-044e4b0ff357 msg: {"candidate":"candidate:3317750581 1 udp 2122260223 172.19.0.4 57770 typ host generation 0 ufrag gtKs network-id 1","sdpMLineIndex":0,"sdpMid":"0"}
```

The funny thing is sometimes it does pick the right address and it works for a while.

Any recommended configuration to work around this?

**Comment by nelenkov** [comment]
Even if running under host networking (see below for crude config, some changes to ports also required; tls removed for easier debugging), webrtc (turn server configured) is still very unreliable. Connects sometimes, sometimes doesn't.

```
static_resources:
  listeners:
  - name: tls_secure
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
                # This is the emulator endpoint for grpc requests.
              - match: { prefix: "/android.emulation.control" }
                route:
                   cluster: emulator_service_grpc
                   max_grpc_timeout: 0s

                # This is the JWT token provider, responsible for handing our secure tokens.
              - match: { prefix: "/token" }
                route: { cluster: jwt_signer }

                # The rest will be available under our webapp.
              - match: { prefix: "/" }
                route: { cluster: nginx }
              cors:
                allow_origin: ["*"]
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          # We setup a JWT authentication endpoint in front of the gRPC engine.
          # This will enforce JWT token validation before we forward the gRPC call
          - name: envoy.filters.http.jwt_authn
            config:
              providers:
                emulator-jwt:
                  issuer: android-emulator@jwt-provider.py
                  audiences:
                  - android.emulation.control.EmulatorController
                  local_jwks:
                    # The secrets that are used by the token service to properly
                    # sign the jwt tokens.
                    filename: /etc/jwt_secrets_pub.jwks
              rules:
              - match: { prefix: "/android.emulation.control.EmulatorController" }
                requires: { provider_name: "emulator-jwt" }
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router

  clusters:
  - name: emulator_service_grpc
    connect_timeout: 0.250s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: emulator_service_grpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8554
  - name: jwt_signer
    connect_timeout: 0.250s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: jwt_signer
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8081
  - name: nginx
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: nginx
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 80
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
